### PR TITLE
add taqpath positive template and primers/probes aliquot protocols

### PR DESCRIPTION
**Pull request by rychen58**
BU/DAMP version of Positive Template and Primers/Probes Aliquot using the Fisher TaqPath COVID-19 Combo kit with multiplex primers/probes set.

### CODE REVIEW

**Comment by dvnstrcklnd** [comment]
Typo in Aliquot Positove Template (TaqPath)

**Comment by dvnstrcklnd** [comment]
Do the inputs or outputs differ between these operation types, like one is a collection or part of a collection and the other isn't? Otherwise there may not be a strong rationale for making different OT's. There looks to be a substantial amount of code duplication in any case. I would suggest that you diff these with the originals, and fix any trivial differences, i.e., TEMPLATE vs. 'Template', single vs. double quotes, ops vs. operations, and then try to extract as much as you can into a module. If there are any substantial differences left, you might be able to take care of it using parameterization.

**Comment by rychen58** [comment]
@dvnstrcklnd Both the inputs of the aliquote positive template and primer/probes protocols of the Taqpath kit are different from the inputs of the CDC protocols.

**Comment by rychen58** [comment]
> Typo in Aliquot Positove Template (TaqPath)

Fixed.

**Pull request merged**
